// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5jZa1eR_uaPaq7U81zpTHmgccEzOTdKs',
    appId: '1:642894985847:web:d85434d48c786e32876472',
    messagingSenderId: '642894985847',
    projectId: 'incaxiasapp',
    authDomain: 'incaxiasapp.firebaseapp.com',
    storageBucket: 'incaxiasapp.appspot.com',
    measurementId: 'G-YWS9KRWLR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTsbMCDo3NVDrDdY98vLNVOgtsD81V3I',
    appId: '1:642894985847:android:f274401c8fe21b60876472',
    messagingSenderId: '642894985847',
    projectId: 'incaxiasapp',
    storageBucket: 'incaxiasapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFpopERhpIGlspau0tg-r6lAVUtGYFxY',
    appId: '1:642894985847:ios:f4ee546dbfafaa82876472',
    messagingSenderId: '642894985847',
    projectId: 'incaxiasapp',
    storageBucket: 'incaxiasapp.appspot.com',
    iosBundleId: 'com.example.incaxiasAppcx',
  );
}
